# Generated by Django 3.2 on 2022-04-27 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='seller',
        ),
        migrations.AddField(
            model_name='inventory',
            name='buyer',
            field=models.CharField(choices=[('seller', 'продавец'), ('buyer', 'покупатель')], default='buyer', max_length=30),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
